name: CI

on:
  push:
    branches: "**"
    pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-12
    steps:
      - run: swift --version
      - uses: actions/checkout@v3
      - run: swift build -c release
